### ISSUE TITLE
Installing fonts

### ISSUE THREAD

**Issue by fedebenelli** [mwallace582/i3blocks-weather#3]
Not really an issue with the script, but I can't get the fonts to work. How do I install them?

**Comment by mwallace582** [comment]
Have you installed the weather icons font? http://erikflowers.github.io/weather-icons/

**Comment by fedebenelli** [comment]
Thank you! At first I was a bit overwhelmed with all the files that download has, but I just needed to put the .ttf file into my ~/.fonts folder. It works great now! I really like it
